# Homebrew formula for Maverick (source of truth lives in the monorepo).
#
# To make it installable, this file is mirrored into a Homebrew *tap* repo
# named `homebrew-tap` under the project's account, so users run:
#
#     brew install cdayAI/tap/maverick
#
# The .github/workflows/homebrew-bump.yml action keeps the `url`/`sha256`
# current: on each `v*` release it resolves the published sdist from PyPI,
# generates hash-locked dependency requirements, and opens a PR updating this
# file (and you sync it to the tap repo).
#
# It installs the checksum-verified `maverick-agent` source plus the installer
# wizard dependencies into an isolated virtualenv, then links the `maverick` CLI
# onto the PATH.
class Maverick < Formula
  include Language::Python::Virtualenv

  desc "Open-source AI agent swarm that runs locally, works for hours, under a budget cap"
  homepage "https://github.com/cdayAI/Maverick"
  url "https://files.pythonhosted.org/packages/source/m/maverick-agent/maverick_agent-0.1.6.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000" # set by homebrew-bump.yml
  license "MIT"

  depends_on "python@3.12"

  def install
    virtualenv_create(libexec, "python3.12")

    # Install the Homebrew-downloaded, checksum-verified sdist first so the
    # stripped, hash-locked dependency set can satisfy packages that declare a
    # runtime dependency on maverick-agent without resolving it from PyPI.
    system libexec/"bin/pip", "install", "--no-deps", "--no-build-isolation", buildpath

    requirements = libexec/"requirements.txt"
    requirements.write(File.read(__FILE__).split(/^__END__\n/, 2).fetch(1))
    system libexec/"bin/pip", "install", "--require-hashes", "--only-binary", ":all:", "-r", requirements
    bin.install_symlink Dir[libexec/"bin/maverick"]
  end

  test do
    # `maverick version` prints the installed package versions; assert this
    # formula's version shows up, proving the CLI installed and runs.
    assert_match version.to_s, shell_output("#{bin}/maverick version")
  end
end

__END__
# Hash-locked runtime requirements are generated by homebrew-bump.yml.
# The initial placeholder formula is intentionally not installable until the
# first release bump writes the exact transitive dependency set and hashes.
